### ISSUE TITLE
Internacionalización no completada

### ISSUE THREAD

**Issue by roberjc** [juagarfer4/EGCDeliberaciones1516#3]
Existe texto en la aplicación que no se ha traducido al inglés, sobre todo en la vista de inicio y el pie de página. El resto de vistas habría que revisarlas y limpiar mensajes en desuso.

**Comment by JuanGarciaIFE** [comment]
Se soluciona la incidencia.

Se ha procedido a la internacionalización de toda la aplicación siguiendo las directivas acordadas en la asignatura Diseño y Pruebas
