### ISSUE TITLE
Test de integración

### ISSUE THREAD

**Issue by JuanGarciaIFE** [juagarfer4/EGCDeliberaciones1516#7]
Haciendo un repaso a los test unitarios realizados en la aplicación me he dado cuenta de que no existe ninguno que compruebe que la integración con autenticación funciona.

**Comment by franmac23** [comment]
Se ha creado un test que comprueba el puente entre Auth y Deliberaciones.

En concreto, se ha definido una llamada a la API de Auth que comprueba que un usuario y su token generado se correspondan con un usuario persistido en la base de datos de Auth.
